// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: context_snapshots.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThreadContextSnapshotForTrigger = `-- name: GetThreadContextSnapshotForTrigger :one
SELECT id, session_id, thread_id, trigger_event_id, parent_snapshot_id, snapshot_ordinal, transcript_trigger_event_ids, messages, projection, context_policy_version, created_at
FROM thread_context_snapshots
WHERE session_id = $1
  AND thread_id = $2
  AND trigger_event_id = $3
`

type GetThreadContextSnapshotForTriggerParams struct {
	SessionID      string
	ThreadID       string
	TriggerEventID string
}

func (q *Queries) GetThreadContextSnapshotForTrigger(ctx context.Context, arg GetThreadContextSnapshotForTriggerParams) (ThreadContextSnapshot, error) {
	row := q.db.QueryRow(ctx, getThreadContextSnapshotForTrigger, arg.SessionID, arg.ThreadID, arg.TriggerEventID)
	var i ThreadContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ThreadID,
		&i.TriggerEventID,
		&i.ParentSnapshotID,
		&i.SnapshotOrdinal,
		&i.TranscriptTriggerEventIds,
		&i.Messages,
		&i.Projection,
		&i.ContextPolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertThreadContextSnapshot = `-- name: InsertThreadContextSnapshot :exec

INSERT INTO thread_context_snapshots (
    id,
    session_id,
    thread_id,
    trigger_event_id,
    parent_snapshot_id,
    transcript_trigger_event_ids,
    messages,
    projection,
    context_policy_version,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (session_id, thread_id, trigger_event_id) DO NOTHING
`

type InsertThreadContextSnapshotParams struct {
	ID                        string
	SessionID                 string
	ThreadID                  string
	TriggerEventID            string
	ParentSnapshotID          *string
	TranscriptTriggerEventIds []byte
	Messages                  []byte
	Projection                []byte
	ContextPolicyVersion      int32
	CreatedAt                 pgtype.Timestamptz
}

// Immutable Thread context snapshot queries.
func (q *Queries) InsertThreadContextSnapshot(ctx context.Context, arg InsertThreadContextSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertThreadContextSnapshot,
		arg.ID,
		arg.SessionID,
		arg.ThreadID,
		arg.TriggerEventID,
		arg.ParentSnapshotID,
		arg.TranscriptTriggerEventIds,
		arg.Messages,
		arg.Projection,
		arg.ContextPolicyVersion,
		arg.CreatedAt,
	)
	return err
}

const latestThreadContextSnapshot = `-- name: LatestThreadContextSnapshot :one
SELECT id, session_id, thread_id, trigger_event_id, parent_snapshot_id, snapshot_ordinal, transcript_trigger_event_ids, messages, projection, context_policy_version, created_at
FROM thread_context_snapshots
WHERE session_id = $1
  AND thread_id = $2
ORDER BY snapshot_ordinal DESC
LIMIT 1
`

type LatestThreadContextSnapshotParams struct {
	SessionID string
	ThreadID  string
}

func (q *Queries) LatestThreadContextSnapshot(ctx context.Context, arg LatestThreadContextSnapshotParams) (ThreadContextSnapshot, error) {
	row := q.db.QueryRow(ctx, latestThreadContextSnapshot, arg.SessionID, arg.ThreadID)
	var i ThreadContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ThreadID,
		&i.TriggerEventID,
		&i.ParentSnapshotID,
		&i.SnapshotOrdinal,
		&i.TranscriptTriggerEventIds,
		&i.Messages,
		&i.Projection,
		&i.ContextPolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}
