// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: journal.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeAttemptForTurn = `-- name: ActiveAttemptForTurn :one
SELECT id
FROM turn_attempts
WHERE session_id = $1 AND trigger_event_id = $2 AND state = 'active'
LIMIT 1
FOR UPDATE
`

type ActiveAttemptForTurnParams struct {
	SessionID      string
	TriggerEventID string
}

// ActiveAttemptForTurn returns the id of the turn's active attempt, if any.
func (q *Queries) ActiveAttemptForTurn(ctx context.Context, arg ActiveAttemptForTurnParams) (string, error) {
	row := q.db.QueryRow(ctx, activeAttemptForTurn, arg.SessionID, arg.TriggerEventID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const completeToolStep = `-- name: CompleteToolStep :execrows
UPDATE tool_steps
SET state = 'completed', result = $1, finished_at = $2, updated_at = $3
WHERE id = $4 AND state = 'started'
`

type CompleteToolStepParams struct {
	Result     []byte
	FinishedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         string
}

// CompleteToolStep advances started -> completed with a durable result.
func (q *Queries) CompleteToolStep(ctx context.Context, arg CompleteToolStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeToolStep,
		arg.Result,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countNonCompletedStepsForAttempt = `-- name: CountNonCompletedStepsForAttempt :one
SELECT COUNT(*)::int AS n FROM tool_steps WHERE attempt_id = $1 AND state <> 'completed'
`

// CountNonCompletedStepsForAttempt counts steps not in completed state — a
// completed attempt requires every step to carry a durable result.
func (q *Queries) CountNonCompletedStepsForAttempt(ctx context.Context, attemptID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNonCompletedStepsForAttempt, attemptID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countStartedStepsForAttempt = `-- name: CountStartedStepsForAttempt :one
SELECT COUNT(*)::int AS n FROM tool_steps WHERE attempt_id = $1 AND state = 'started'
`

// CountStartedStepsForAttempt counts steps still in the started (unclassified)
// state for an attempt — a terminal attempt must have none.
func (q *Queries) CountStartedStepsForAttempt(ctx context.Context, attemptID string) (int32, error) {
	row := q.db.QueryRow(ctx, countStartedStepsForAttempt, attemptID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const finishTurnAttempt = `-- name: FinishTurnAttempt :execrows
UPDATE turn_attempts
SET state = $1, error = $2, updated_at = $3, finished_at = $4
WHERE id = $5 AND state = 'active'
`

type FinishTurnAttemptParams struct {
	State      string
	Error      *string
	UpdatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	ID         string
}

// FinishTurnAttempt closes an active attempt. The from-state guard makes the
// transition safe under concurrency; the Go caller checks rows-affected.
func (q *Queries) FinishTurnAttempt(ctx context.Context, arg FinishTurnAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishTurnAttempt,
		arg.State,
		arg.Error,
		arg.UpdatedAt,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getToolStep = `-- name: GetToolStep :one
SELECT id, attempt_id, ordinal, tool_use_event_id, tool_name, input, state, result,
       created_at, updated_at, started_at, finished_at
FROM tool_steps
WHERE id = $1
`

func (q *Queries) GetToolStep(ctx context.Context, id string) (ToolStep, error) {
	row := q.db.QueryRow(ctx, getToolStep, id)
	var i ToolStep
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Ordinal,
		&i.ToolUseEventID,
		&i.ToolName,
		&i.Input,
		&i.State,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTurnAttempt = `-- name: GetTurnAttempt :one
SELECT id, session_id, trigger_event_id, attempt_no, state, error, created_at, updated_at, finished_at
FROM turn_attempts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTurnAttempt(ctx context.Context, id string) (TurnAttempt, error) {
	row := q.db.QueryRow(ctx, getTurnAttempt, id)
	var i TurnAttempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TriggerEventID,
		&i.AttemptNo,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertToolStep = `-- name: InsertToolStep :exec
INSERT INTO tool_steps
  (id, attempt_id, ordinal, tool_use_event_id, tool_name, input, state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'prepared', $7, $8)
`

type InsertToolStepParams struct {
	ID             string
	AttemptID      string
	Ordinal        int32
	ToolUseEventID string
	ToolName       string
	Input          []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertToolStep(ctx context.Context, arg InsertToolStepParams) error {
	_, err := q.db.Exec(ctx, insertToolStep,
		arg.ID,
		arg.AttemptID,
		arg.Ordinal,
		arg.ToolUseEventID,
		arg.ToolName,
		arg.Input,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTurnAttempt = `-- name: InsertTurnAttempt :exec
INSERT INTO turn_attempts (id, session_id, trigger_event_id, attempt_no, state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTurnAttemptParams struct {
	ID             string
	SessionID      string
	TriggerEventID string
	AttemptNo      int32
	State          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertTurnAttempt(ctx context.Context, arg InsertTurnAttemptParams) error {
	_, err := q.db.Exec(ctx, insertTurnAttempt,
		arg.ID,
		arg.SessionID,
		arg.TriggerEventID,
		arg.AttemptNo,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const markStartedStepsAmbiguousForAttempt = `-- name: MarkStartedStepsAmbiguousForAttempt :execrows
UPDATE tool_steps
SET state = 'ambiguous', finished_at = $1, updated_at = $2
WHERE attempt_id = $3 AND state = 'started'
`

type MarkStartedStepsAmbiguousForAttemptParams struct {
	FinishedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AttemptID  string
}

// MarkStartedStepsAmbiguousForAttempt fences an interrupted attempt after its
// canceled Activity has acknowledged cancellation. A step that crossed started
// may have changed the outside world; recording ambiguous is the only honest
// terminal classification when no durable result exists.
func (q *Queries) MarkStartedStepsAmbiguousForAttempt(ctx context.Context, arg MarkStartedStepsAmbiguousForAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, markStartedStepsAmbiguousForAttempt, arg.FinishedAt, arg.UpdatedAt, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markToolStepAmbiguous = `-- name: MarkToolStepAmbiguous :execrows
UPDATE tool_steps
SET state = 'ambiguous', finished_at = $1, updated_at = $2
WHERE id = $3 AND state = 'started'
`

type MarkToolStepAmbiguousParams struct {
	FinishedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ID         string
}

// MarkToolStepAmbiguous advances started -> ambiguous (no trustworthy result).
func (q *Queries) MarkToolStepAmbiguous(ctx context.Context, arg MarkToolStepAmbiguousParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolStepAmbiguous, arg.FinishedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextAttemptNo = `-- name: NextAttemptNo :one

SELECT (COALESCE(MAX(attempt_no), 0) + 1)::int AS next_no
FROM turn_attempts
WHERE session_id = $1 AND trigger_event_id = $2
`

type NextAttemptNoParams struct {
	SessionID      string
	TriggerEventID string
}

// Typed queries for the Temporal-path tool-execution journal (turn_attempts,
// tool_steps). Transitions keep an explicit from-state in the WHERE clause and
// the Go layer checks rows-affected to enforce guarded state transitions.
func (q *Queries) NextAttemptNo(ctx context.Context, arg NextAttemptNoParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttemptNo, arg.SessionID, arg.TriggerEventID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const priorToolExecutionForTurn = `-- name: PriorToolExecutionForTurn :one
SELECT EXISTS(
  SELECT 1
  FROM tool_steps ts
  JOIN turn_attempts ta ON ta.id = ts.attempt_id
  WHERE ta.session_id = $1 AND ta.trigger_event_id = $2
    AND ts.state IN ('started', 'completed', 'ambiguous')
) AS prior
`

type PriorToolExecutionForTurnParams struct {
	SessionID      string
	TriggerEventID string
}

// PriorToolExecutionForTurn reports whether any tool step across the turn's
// attempts has crossed the side-effect boundary (started/completed/ambiguous),
// i.e. the turn cannot be freshly re-run without risking a silent replay.
func (q *Queries) PriorToolExecutionForTurn(ctx context.Context, arg PriorToolExecutionForTurnParams) (bool, error) {
	row := q.db.QueryRow(ctx, priorToolExecutionForTurn, arg.SessionID, arg.TriggerEventID)
	var prior bool
	err := row.Scan(&prior)
	return prior, err
}

const startToolStep = `-- name: StartToolStep :execrows
UPDATE tool_steps AS ts
SET state = 'started', started_at = $1, updated_at = $2
FROM turn_attempts AS ta
WHERE ts.id = $3
  AND ts.state = 'prepared'
  AND ta.id = ts.attempt_id
  AND ta.state = 'active'
`

type StartToolStepParams struct {
	StartedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ID        string
}

// StartToolStep advances prepared -> started, stamping started_at. The from-state
// guard prevents re-starting, and the parent-attempt guard fences an overlapping
// stale Activity after recovery has failed its attempt. The caller checks
// rows-affected.
func (q *Queries) StartToolStep(ctx context.Context, arg StartToolStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, startToolStep, arg.StartedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startedStepsForTurn = `-- name: StartedStepsForTurn :many
SELECT ts.id
FROM tool_steps ts
JOIN turn_attempts ta ON ta.id = ts.attempt_id
WHERE ta.session_id = $1 AND ta.trigger_event_id = $2 AND ts.state = 'started'
`

type StartedStepsForTurnParams struct {
	SessionID      string
	TriggerEventID string
}

// StartedStepsForTurn returns the ids of every started (unclassified) tool step
// across all attempts of a turn — the recovery input.
func (q *Queries) StartedStepsForTurn(ctx context.Context, arg StartedStepsForTurnParams) ([]string, error) {
	rows, err := q.db.Query(ctx, startedStepsForTurn, arg.SessionID, arg.TriggerEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolStepConflict = `-- name: ToolStepConflict :one
SELECT EXISTS(
  SELECT 1 FROM tool_steps
  WHERE (attempt_id = $1 AND ordinal = $2) OR tool_use_event_id = $3
) AS conflict
`

type ToolStepConflictParams struct {
	AttemptID      string
	Ordinal        int32
	ToolUseEventID string
}

// ToolStepConflict reports whether a step with the same (attempt, ordinal) or the
// same tool_use_event_id already exists.
func (q *Queries) ToolStepConflict(ctx context.Context, arg ToolStepConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, toolStepConflict, arg.AttemptID, arg.Ordinal, arg.ToolUseEventID)
	var conflict bool
	err := row.Scan(&conflict)
	return conflict, err
}
