// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcp.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMCPDiscoverySnapshot = `-- name: GetMCPDiscoverySnapshot :one
SELECT session_id, server_name, server_url, tools, created_at
FROM mcp_discovery_snapshots
WHERE session_id = $1 AND server_name = $2
`

type GetMCPDiscoverySnapshotParams struct {
	SessionID  string
	ServerName string
}

func (q *Queries) GetMCPDiscoverySnapshot(ctx context.Context, arg GetMCPDiscoverySnapshotParams) (McpDiscoverySnapshot, error) {
	row := q.db.QueryRow(ctx, getMCPDiscoverySnapshot, arg.SessionID, arg.ServerName)
	var i McpDiscoverySnapshot
	err := row.Scan(
		&i.SessionID,
		&i.ServerName,
		&i.ServerUrl,
		&i.Tools,
		&i.CreatedAt,
	)
	return i, err
}

const insertMCPDiscoverySnapshot = `-- name: InsertMCPDiscoverySnapshot :exec
INSERT INTO mcp_discovery_snapshots (
    session_id, server_name, server_url, tools, created_at
)
VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (session_id, server_name) DO NOTHING
`

type InsertMCPDiscoverySnapshotParams struct {
	SessionID  string
	ServerName string
	ServerUrl  string
	Tools      []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertMCPDiscoverySnapshot(ctx context.Context, arg InsertMCPDiscoverySnapshotParams) error {
	_, err := q.db.Exec(ctx, insertMCPDiscoverySnapshot,
		arg.SessionID,
		arg.ServerName,
		arg.ServerUrl,
		arg.Tools,
		arg.CreatedAt,
	)
	return err
}
