// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID         string
	Version    int32
	Name       string
	Body       []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

type Environment struct {
	ID         string
	Name       string
	ConfigType string
	Body       []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

type Event struct {
	ID          string
	SessionID   string
	Seq         int64
	Type        string
	Payload     []byte
	TurnEventID *string
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type OrchestrationOutbox struct {
	SessionID     string
	MaxEventSeq   int64
	EnqueuedAt    pgtype.Timestamptz
	Attempts      int32
	LastAttemptAt pgtype.Timestamptz
	LastError     *string
}

type PendingAction struct {
	ID               string
	SessionID        string
	ActionEventID    string
	Kind             string
	ResolvingEventID *string
	CreatedAt        pgtype.Timestamptz
	ResolvedAt       pgtype.Timestamptz
}

type Session struct {
	ID            string
	Status        string
	Body          []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AgentID       *string
	AgentVersion  *int32
	EnvironmentID *string
	ArchivedAt    pgtype.Timestamptz
	DeletingAt    pgtype.Timestamptz
}

type SessionSandbox struct {
	SessionID  string
	Provider   string
	ExternalID string
	SpecHash   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToolStep struct {
	ID             string
	AttemptID      string
	Ordinal        int32
	ToolUseEventID string
	ToolName       string
	Input          []byte
	State          string
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type TurnAttempt struct {
	ID             string
	SessionID      string
	TriggerEventID string
	AttemptNo      int32
	State          string
	Error          *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}
