// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingAction = `-- name: ClaimPendingAction :execrows
UPDATE pending_actions
SET resolving_event_id = $1
WHERE session_id = $2
  AND action_event_id = $3
  AND resolving_event_id IS NULL
  AND resolved_at IS NULL
`

type ClaimPendingActionParams struct {
	ResolvingEventID *string
	SessionID        string
	ActionEventID    string
}

func (q *Queries) ClaimPendingAction(ctx context.Context, arg ClaimPendingActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimPendingAction, arg.ResolvingEventID, arg.SessionID, arg.ActionEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingActionForUpdate = `-- name: GetPendingActionForUpdate :one
SELECT id, session_id, action_event_id, kind, resolving_event_id, created_at, resolved_at
FROM pending_actions
WHERE session_id = $1 AND action_event_id = $2
FOR UPDATE
`

type GetPendingActionForUpdateParams struct {
	SessionID     string
	ActionEventID string
}

func (q *Queries) GetPendingActionForUpdate(ctx context.Context, arg GetPendingActionForUpdateParams) (PendingAction, error) {
	row := q.db.QueryRow(ctx, getPendingActionForUpdate, arg.SessionID, arg.ActionEventID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ActionEventID,
		&i.Kind,
		&i.ResolvingEventID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const hasUnclaimedPendingActions = `-- name: HasUnclaimedPendingActions :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1
      AND resolved_at IS NULL
      AND resolving_event_id IS NULL
) AS unclaimed
`

func (q *Queries) HasUnclaimedPendingActions(ctx context.Context, sessionID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnclaimedPendingActions, sessionID)
	var unclaimed bool
	err := row.Scan(&unclaimed)
	return unclaimed, err
}

const hasUnresolvedPendingActions = `-- name: HasUnresolvedPendingActions :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1 AND resolved_at IS NULL
) AS unresolved
`

func (q *Queries) HasUnresolvedPendingActions(ctx context.Context, sessionID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnresolvedPendingActions, sessionID)
	var unresolved bool
	err := row.Scan(&unresolved)
	return unresolved, err
}

const insertPendingAction = `-- name: InsertPendingAction :exec

INSERT INTO pending_actions (
    id, session_id, action_event_id, kind, resolving_event_id, created_at, resolved_at
)
VALUES (
    $1, $2, $3, $4, NULL, $5, NULL
)
`

type InsertPendingActionParams struct {
	ID            string
	SessionID     string
	ActionEventID string
	Kind          string
	CreatedAt     pgtype.Timestamptz
}

// Typed queries for durable client-action gates on the Temporal/PostgreSQL
// path. Callers hold the session row lock, so park, admission claim, and resume
// completion serialize with the public event ledger and session projection.
func (q *Queries) InsertPendingAction(ctx context.Context, arg InsertPendingActionParams) error {
	_, err := q.db.Exec(ctx, insertPendingAction,
		arg.ID,
		arg.SessionID,
		arg.ActionEventID,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const isUnresolvedPendingResolution = `-- name: IsUnresolvedPendingResolution :one
SELECT EXISTS(
    SELECT 1
    FROM pending_actions
    WHERE session_id = $1
      AND resolving_event_id = $2
      AND resolved_at IS NULL
) AS pending_resume
`

type IsUnresolvedPendingResolutionParams struct {
	SessionID        string
	ResolvingEventID *string
}

// IsUnresolvedPendingResolution distinguishes a processed-on-receipt client
// result that still has to drive its resume turn from an already completed
// trigger. user.custom_tool_result carries processed_at at admission by public
// contract, so processed_at alone cannot be the turn-completion idempotency key.
func (q *Queries) IsUnresolvedPendingResolution(ctx context.Context, arg IsUnresolvedPendingResolutionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUnresolvedPendingResolution, arg.SessionID, arg.ResolvingEventID)
	var pending_resume bool
	err := row.Scan(&pending_resume)
	return pending_resume, err
}

const listUnresolvedPendingActions = `-- name: ListUnresolvedPendingActions :many
SELECT id, session_id, action_event_id, kind, resolving_event_id, created_at, resolved_at
FROM pending_actions
WHERE session_id = $1 AND resolved_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListUnresolvedPendingActions(ctx context.Context, sessionID string) ([]PendingAction, error) {
	rows, err := q.db.Query(ctx, listUnresolvedPendingActions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingAction{}
	for rows.Next() {
		var i PendingAction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ActionEventID,
			&i.Kind,
			&i.ResolvingEventID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePendingActionsForEvents = `-- name: ResolvePendingActionsForEvents :execrows
UPDATE pending_actions
SET resolved_at = $1
WHERE session_id = $2
  AND resolving_event_id = ANY($3::text[])
  AND resolved_at IS NULL
`

type ResolvePendingActionsForEventsParams struct {
	ResolvedAt        pgtype.Timestamptz
	SessionID         string
	ResolvingEventIds []string
}

// ResolvePendingActionsForEvents closes one complete client-action barrier.
// The caller validates that the supplied ids exactly match every unresolved
// row before executing this update under the session lock.
func (q *Queries) ResolvePendingActionsForEvents(ctx context.Context, arg ResolvePendingActionsForEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolvePendingActionsForEvents, arg.ResolvedAt, arg.SessionID, arg.ResolvingEventIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePendingActionsForTrigger = `-- name: ResolvePendingActionsForTrigger :execrows
UPDATE pending_actions
SET resolved_at = $1
WHERE session_id = $2
  AND resolving_event_id = $3
  AND resolved_at IS NULL
`

type ResolvePendingActionsForTriggerParams struct {
	ResolvedAt       pgtype.Timestamptz
	SessionID        string
	ResolvingEventID *string
}

func (q *Queries) ResolvePendingActionsForTrigger(ctx context.Context, arg ResolvePendingActionsForTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolvePendingActionsForTrigger, arg.ResolvedAt, arg.SessionID, arg.ResolvingEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
