// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resources.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAgent = `-- name: ArchiveAgent :execrows
UPDATE agents
SET archived_at = COALESCE(archived_at, $1)
WHERE id = $2
`

type ArchiveAgentParams struct {
	ArchivedAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAgent, arg.ArchivedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEnvironmentIfUnreferenced = `-- name: DeleteEnvironmentIfUnreferenced :execrows
DELETE FROM environments AS environment
WHERE environment.id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM sessions
      WHERE sessions.environment_id = environment.id
  )
`

func (q *Queries) DeleteEnvironmentIfUnreferenced(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironmentIfUnreferenced, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMarkedSession = `-- name: DeleteMarkedSession :execrows
DELETE FROM sessions
WHERE id = $1 AND deleting_at IS NOT NULL
`

func (q *Queries) DeleteMarkedSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarkedSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const environmentExists = `-- name: EnvironmentExists :one
SELECT EXISTS(SELECT 1 FROM environments WHERE id = $1)
`

func (q *Queries) EnvironmentExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, environmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT id, version, name, body, created_at, updated_at, archived_at
FROM agents
WHERE id = $1 AND version = $2
`

type GetAgentVersionParams struct {
	ID      string
	Version int32
}

func (q *Queries) GetAgentVersion(ctx context.Context, arg GetAgentVersionParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, arg.ID, arg.Version)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, config_type, body, created_at, updated_at, archived_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigType,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getLatestAgent = `-- name: GetLatestAgent :one
SELECT id, version, name, body, created_at, updated_at, archived_at
FROM agents
WHERE id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, getLatestAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertAgentVersion = `-- name: InsertAgentVersion :exec

INSERT INTO agents (id, version, name, body, created_at, updated_at, archived_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAgentVersionParams struct {
	ID         string
	Version    int32
	Name       string
	Body       []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

// Typed resource queries for the PostgreSQL HTTP control plane.
func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) error {
	_, err := q.db.Exec(ctx, insertAgentVersion,
		arg.ID,
		arg.Version,
		arg.Name,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
	)
	return err
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT id, version, name, body, created_at, updated_at, archived_at
FROM agents
WHERE id = $1
ORDER BY version
`

func (q *Queries) ListAgentVersions(ctx context.Context, id string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletingSessionIDs = `-- name: ListDeletingSessionIDs :many
SELECT id
FROM sessions
WHERE deleting_at IS NOT NULL
ORDER BY deleting_at, id
LIMIT $1
`

func (q *Queries) ListDeletingSessionIDs(ctx context.Context, rowLimit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeletingSessionIDs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveAgentVersion = `-- name: LockActiveAgentVersion :one

SELECT id
FROM agents
WHERE id = $1 AND version = $2 AND archived_at IS NULL
FOR SHARE
`

type LockActiveAgentVersionParams struct {
	ID      string
	Version int32
}

// List Agents and List Environments are keyset-paginated with request-dependent
// filters, so their statements are composed in internal/pg/api_store.go beside
// List Sessions rather than being pinned here as static queries.
func (q *Queries) LockActiveAgentVersion(ctx context.Context, arg LockActiveAgentVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, lockActiveAgentVersion, arg.ID, arg.Version)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockActiveEnvironment = `-- name: LockActiveEnvironment :one
SELECT id
FROM environments
WHERE id = $1 AND archived_at IS NULL
FOR SHARE
`

func (q *Queries) LockActiveEnvironment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockActiveEnvironment, id)
	err := row.Scan(&id)
	return id, err
}

const lockLatestAgent = `-- name: LockLatestAgent :one
SELECT id, version, name, body, created_at, updated_at, archived_at
FROM agents
WHERE id = $1
ORDER BY version DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockLatestAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, lockLatestAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const markSessionDeleting = `-- name: MarkSessionDeleting :exec
UPDATE sessions
SET deleting_at = COALESCE(deleting_at, $1)
WHERE id = $2
`

type MarkSessionDeletingParams struct {
	DeletingAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) MarkSessionDeleting(ctx context.Context, arg MarkSessionDeletingParams) error {
	_, err := q.db.Exec(ctx, markSessionDeleting, arg.DeletingAt, arg.ID)
	return err
}

const updateSessionProjection = `-- name: UpdateSessionProjection :exec
UPDATE sessions
SET status = $1,
    body = $2,
    updated_at = $3,
    archived_at = $4
WHERE id = $5
`

type UpdateSessionProjectionParams struct {
	Status     string
	Body       []byte
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateSessionProjection(ctx context.Context, arg UpdateSessionProjectionParams) error {
	_, err := q.db.Exec(ctx, updateSessionProjection,
		arg.Status,
		arg.Body,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.ID,
	)
	return err
}

const upsertEnvironment = `-- name: UpsertEnvironment :exec
INSERT INTO environments (
    id, name, config_type, body, created_at, updated_at, archived_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    config_type = EXCLUDED.config_type,
    body = EXCLUDED.body,
    updated_at = EXCLUDED.updated_at,
    archived_at = EXCLUDED.archived_at
`

type UpsertEnvironmentParams struct {
	ID         string
	Name       string
	ConfigType string
	Body       []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironment,
		arg.ID,
		arg.Name,
		arg.ConfigType,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
	)
	return err
}
