// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSandboxBinding = `-- name: DeleteSandboxBinding :execrows
DELETE FROM session_sandboxes
WHERE session_id = $1
  AND provider = $2
  AND external_id = $3
`

type DeleteSandboxBindingParams struct {
	SessionID  string
	Provider   string
	ExternalID string
}

func (q *Queries) DeleteSandboxBinding(ctx context.Context, arg DeleteSandboxBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSandboxBinding, arg.SessionID, arg.Provider, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSandboxProvisioningIntent = `-- name: DeleteSandboxProvisioningIntent :execrows
DELETE FROM sandbox_provisioning_intents
WHERE session_id = $1
  AND provider = $2
  AND spec_hash = $3
`

type DeleteSandboxProvisioningIntentParams struct {
	SessionID string
	Provider  string
	SpecHash  string
}

func (q *Queries) DeleteSandboxProvisioningIntent(ctx context.Context, arg DeleteSandboxProvisioningIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSandboxProvisioningIntent, arg.SessionID, arg.Provider, arg.SpecHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSandboxProvisioningIntentBySession = `-- name: DeleteSandboxProvisioningIntentBySession :exec
DELETE FROM sandbox_provisioning_intents
WHERE session_id = $1
`

func (q *Queries) DeleteSandboxProvisioningIntentBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSandboxProvisioningIntentBySession, sessionID)
	return err
}

const getSandboxBinding = `-- name: GetSandboxBinding :one
SELECT session_id, provider, external_id, spec_hash, created_at, updated_at
FROM session_sandboxes
WHERE session_id = $1
`

func (q *Queries) GetSandboxBinding(ctx context.Context, sessionID string) (SessionSandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxBinding, sessionID)
	var i SessionSandbox
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.ExternalID,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSandboxProvisioningIntent = `-- name: GetSandboxProvisioningIntent :one

SELECT session_id, provider, spec, spec_hash, created_at, updated_at
FROM sandbox_provisioning_intents
WHERE session_id = $1
`

// Durable session-to-provider sandbox ownership.
func (q *Queries) GetSandboxProvisioningIntent(ctx context.Context, sessionID string) (SandboxProvisioningIntent, error) {
	row := q.db.QueryRow(ctx, getSandboxProvisioningIntent, sessionID)
	var i SandboxProvisioningIntent
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.Spec,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSandboxProvisioningIntents = `-- name: ListSandboxProvisioningIntents :many
SELECT intent.session_id,
       intent.provider,
       intent.spec,
       intent.spec_hash,
       intent.created_at,
       intent.updated_at,
       session.deleting_at
FROM sandbox_provisioning_intents AS intent
JOIN sessions AS session ON session.id = intent.session_id
WHERE intent.provider = $1
ORDER BY intent.created_at, intent.session_id
LIMIT $2
`

type ListSandboxProvisioningIntentsParams struct {
	Provider string
	RowLimit int32
}

type ListSandboxProvisioningIntentsRow struct {
	SessionID  string
	Provider   string
	Spec       []byte
	SpecHash   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletingAt pgtype.Timestamptz
}

func (q *Queries) ListSandboxProvisioningIntents(ctx context.Context, arg ListSandboxProvisioningIntentsParams) ([]ListSandboxProvisioningIntentsRow, error) {
	rows, err := q.db.Query(ctx, listSandboxProvisioningIntents, arg.Provider, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSandboxProvisioningIntentsRow{}
	for rows.Next() {
		var i ListSandboxProvisioningIntentsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Provider,
			&i.Spec,
			&i.SpecHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSandboxBinding = `-- name: PutSandboxBinding :one
INSERT INTO session_sandboxes (
    session_id, provider, external_id, spec_hash, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (session_id) DO UPDATE SET
    updated_at = session_sandboxes.updated_at
RETURNING session_id, provider, external_id, spec_hash, created_at, updated_at
`

type PutSandboxBindingParams struct {
	SessionID  string
	Provider   string
	ExternalID string
	SpecHash   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) PutSandboxBinding(ctx context.Context, arg PutSandboxBindingParams) (SessionSandbox, error) {
	row := q.db.QueryRow(ctx, putSandboxBinding,
		arg.SessionID,
		arg.Provider,
		arg.ExternalID,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SessionSandbox
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.ExternalID,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putSandboxProvisioningIntent = `-- name: PutSandboxProvisioningIntent :one
INSERT INTO sandbox_provisioning_intents (
    session_id, provider, spec, spec_hash, created_at, updated_at
)
SELECT
    $1, $2, $3, $4, $5, $6
FROM sessions
WHERE id = $1 AND deleting_at IS NULL
ON CONFLICT (session_id) DO UPDATE SET
    updated_at = sandbox_provisioning_intents.updated_at
RETURNING session_id, provider, spec, spec_hash, created_at, updated_at
`

type PutSandboxProvisioningIntentParams struct {
	SessionID string
	Provider  string
	Spec      []byte
	SpecHash  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) PutSandboxProvisioningIntent(ctx context.Context, arg PutSandboxProvisioningIntentParams) (SandboxProvisioningIntent, error) {
	row := q.db.QueryRow(ctx, putSandboxProvisioningIntent,
		arg.SessionID,
		arg.Provider,
		arg.Spec,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SandboxProvisioningIntent
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.Spec,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
