// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSandboxBinding = `-- name: DeleteSandboxBinding :execrows
DELETE FROM session_sandboxes
WHERE session_id = $1
  AND provider = $2
  AND external_id = $3
`

type DeleteSandboxBindingParams struct {
	SessionID  string
	Provider   string
	ExternalID string
}

func (q *Queries) DeleteSandboxBinding(ctx context.Context, arg DeleteSandboxBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSandboxBinding, arg.SessionID, arg.Provider, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSandboxBinding = `-- name: GetSandboxBinding :one

SELECT session_id, provider, external_id, spec_hash, created_at, updated_at
FROM session_sandboxes
WHERE session_id = $1
`

// Durable session-to-provider sandbox ownership.
func (q *Queries) GetSandboxBinding(ctx context.Context, sessionID string) (SessionSandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxBinding, sessionID)
	var i SessionSandbox
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.ExternalID,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putSandboxBinding = `-- name: PutSandboxBinding :one
INSERT INTO session_sandboxes (
    session_id, provider, external_id, spec_hash, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (session_id) DO UPDATE SET
    updated_at = session_sandboxes.updated_at
RETURNING session_id, provider, external_id, spec_hash, created_at, updated_at
`

type PutSandboxBindingParams struct {
	SessionID  string
	Provider   string
	ExternalID string
	SpecHash   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) PutSandboxBinding(ctx context.Context, arg PutSandboxBindingParams) (SessionSandbox, error) {
	row := q.db.QueryRow(ctx, putSandboxBinding,
		arg.SessionID,
		arg.Provider,
		arg.ExternalID,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SessionSandbox
	err := row.Scan(
		&i.SessionID,
		&i.Provider,
		&i.ExternalID,
		&i.SpecHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
