// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transcript.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProviderTranscriptTurn = `-- name: InsertProviderTranscriptTurn :exec

INSERT INTO provider_transcript_turns (
    session_id,
    trigger_event_id,
    committed_through_seq,
    represented_event_ids,
    messages,
    tool_use_mappings,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (session_id, trigger_event_id) DO NOTHING
`

type InsertProviderTranscriptTurnParams struct {
	SessionID           string
	TriggerEventID      string
	CommittedThroughSeq int64
	RepresentedEventIds []byte
	Messages            []byte
	ToolUseMappings     []byte
	CreatedAt           pgtype.Timestamptz
}

// Provider transcript queries. Turn deltas are inserted in the same transaction
// that commits their public events and marks the trigger processed.
func (q *Queries) InsertProviderTranscriptTurn(ctx context.Context, arg InsertProviderTranscriptTurnParams) error {
	_, err := q.db.Exec(ctx, insertProviderTranscriptTurn,
		arg.SessionID,
		arg.TriggerEventID,
		arg.CommittedThroughSeq,
		arg.RepresentedEventIds,
		arg.Messages,
		arg.ToolUseMappings,
		arg.CreatedAt,
	)
	return err
}

const listProviderTranscriptTurns = `-- name: ListProviderTranscriptTurns :many
SELECT
    session_id,
    trigger_event_id,
    turn_ordinal,
    committed_through_seq,
    represented_event_ids,
    messages,
    tool_use_mappings,
    created_at
FROM provider_transcript_turns
WHERE session_id = $1
ORDER BY turn_ordinal
`

func (q *Queries) ListProviderTranscriptTurns(ctx context.Context, sessionID string) ([]ProviderTranscriptTurn, error) {
	rows, err := q.db.Query(ctx, listProviderTranscriptTurns, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderTranscriptTurn{}
	for rows.Next() {
		var i ProviderTranscriptTurn
		if err := rows.Scan(
			&i.SessionID,
			&i.TriggerEventID,
			&i.TurnOrdinal,
			&i.CommittedThroughSeq,
			&i.RepresentedEventIds,
			&i.Messages,
			&i.ToolUseMappings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
